# Generated by Django 4.1.1 on 2022-09-08 18:14

from django.db import migrations, models
import django.db.models.deletion
import league.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('PR', 'Premier'), ('DIV1', 'Division I'), ('DIV2', 'Division II')], default='PR', max_length=15, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=100, unique=True)),
                ('team_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to=league.models.save_team_image, verbose_name='Team Image')),
                ('hometown', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='league.level')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100, unique=True)),
                ('player_height', models.IntegerField(blank=True)),
                ('player_weight', models.IntegerField(blank=True)),
                ('player_age', models.IntegerField(blank=True)),
                ('player_name', models.CharField(max_length=250)),
                ('player_position', models.CharField(max_length=100, verbose_name='position')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=league.models.save_player_files, verbose_name='Video')),
                ('player_image', models.ImageField(blank=True, upload_to=league.models.save_player_image, verbose_name='Player ProfilePics')),
                ('player_stats', models.FileField(blank=True, upload_to=league.models.save_player_files, verbose_name='Stats')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.level')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.team')),
            ],
        ),
    ]
