# Generated by Django 4.1.1 on 2022-09-09 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppg', models.PositiveSmallIntegerField()),
                ('rpg', models.PositiveSmallIntegerField()),
                ('apg', models.PositiveSmallIntegerField()),
                ('spg', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pstats', to='league.player')),
            ],
        ),
    ]
