# Generated by Django 4.1.1 on 2022-09-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_type',
            field=models.CharField(choices=[('PREMIER', 'Premier'), ('DIVISION I', 'Division I'), ('DIVISION II', 'Division II')], default='PREMIER', max_length=15, unique=True),
        ),
    ]
