# Generated by Django 4.1.1 on 2022-09-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_level_level_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'ordering': ('-ppg', 'player')},
        ),
    ]
